#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ecj
Version  : 1
Release  : 1
URL      : http://ftp.osuosl.org/pub/eclipse/eclipse/downloads/drops4/R-4.10-201812060815/ecjsrc-4.10.jar
Source0  : http://ftp.osuosl.org/pub/eclipse/eclipse/downloads/drops4/R-4.10-201812060815/ecjsrc-4.10.jar
Source1  : http://archive.eclipse.org/eclipse/downloads/drops4/R-4.10-201812060815/ecj-4.10.jar
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-2.0

%description
No detailed description available

%prep
%setup -q -n META-INF

%build

%install

%files
%defattr(-,root,root,-)
